---
title: "Env_plots"
author: "Eva Egelyng Sigsgaard"
date: "2023-09-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(ggplot2)
library(ggpubr)
library(ggpmisc)
```

```{r get data}

## Get phyloseq object
COSQ_rare2 <- readRDS("../../RDS/COI_no_c2_3reps.rds")

## Get metadata
metadata<-data.frame(sample_data(COSQ_rare2))
#Create extra metadata variables
metadata$sshc<-paste(metadata$substrate_type, metadata$season, metadata$habitat, metadata$cluster, sep="_")

## Get sea distances
areas<-read.table("../../Tekstfiler/COI/Mads_metadata_230921_C19.txt", sep="\t", row.names=1, header=T, check.names=FALSE)

## Get salinities
coord<-read.table("../../Tekstfiler/Across_barcodes/merged_metadata_230427.txt", sep="\t", row.names=1, header=T, check.names=FALSE)
```


```{r dist sed}

jaccard<-read.table("../../Tekstfiler/COI/COI_70/Jaccard_sed.txt")
metadata$sea_dist<-areas$dist_from_C33.km[match(metadata$cluster,areas$Cluster)]
jaccard$sea_dist<-metadata$sea_dist[match(row.names(jaccard),metadata$sshc)]
jaccard$habitat<-metadata$habitat[match(row.names(jaccard),metadata$sshc)]

p<-ggplot(jaccard, aes(x=sea_dist, y=NMDS1, lty=habitat)) +
   geom_point(size=2,aes(color=habitat))+
   scale_color_manual(values = c("yellowgreen", "cornflowerblue","thistle3"),
                     name = "", breaks = sort(unique(metadata$habitat)),
                     labels = sort(unique(metadata$habitat)))+
   scale_x_continuous("Distance by sea (km)") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p
```

```{r dist wat}

jaccard_w<-read.table("../../Tekstfiler/COI/COI_70/Jaccard_wat.txt")
jaccard_w$sea_dist<-metadata$sea_dist[match(row.names(jaccard_w),metadata$sshc)]
jaccard_w$habitat<-metadata$habitat[match(row.names(jaccard_w),metadata$sshc)]

p2<-ggplot(jaccard_w, aes(x=sea_dist, y=NMDS1, lty=habitat)) +
   geom_point(size=2,aes(color=habitat))+
   scale_color_manual(values = c("yellowgreen", "cornflowerblue","thistle3"),
                     name = "", breaks = sort(unique(metadata$habitat)),
                     labels = sort(unique(metadata$habitat)))+
   scale_x_continuous("Distance by sea (km)") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p2
ggsave(file="../../Plots/Env_plots/Sea_dist_COI_both.png",ggarrange(p,p2,ncol=2,nrow=2,align="h",common.legend=TRUE,legend="top"),height=8)
```

```{r salinity sed}

# Add salinity values to dataframe with NMDS scores
metadata$new_name<-paste(metadata$season,metadata$cluster,metadata$habitat,sep="_")
jaccard$new_name<-metadata$new_name[match(row.names(jaccard),metadata$sshc)]
jaccard$salinity<-coord$Salinity[match(jaccard$new_name,row.names(coord))]

p3<-ggplot(jaccard, aes(x=salinity, y=NMDS1, lty=habitat)) +
   geom_point(size=2,aes(color=habitat))+
   scale_color_manual(values = c("yellowgreen", "cornflowerblue","thistle3"),
                     name = "", breaks = sort(unique(metadata$habitat)),
                     labels = sort(unique(metadata$habitat)))+
   scale_x_continuous("Salinity") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p3
```

```{r salinity wat}

jaccard_w$new_name<-metadata$new_name[match(row.names(jaccard_w),metadata$sshc)]
jaccard_w$salinity<-coord$Salinity[match(jaccard_w$new_name,row.names(coord))]

p4<-ggplot(jaccard_w, aes(x=salinity, y=NMDS1, lty=habitat)) +
   geom_point(size=2,aes(color=habitat))+
   scale_color_manual(values = c("yellowgreen", "cornflowerblue","thistle3"),
                     name = "", breaks = sort(unique(metadata$habitat)),
                     labels = sort(unique(metadata$habitat)))+
   scale_x_continuous("Salinity") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p4  
ggsave(file="../../Plots/Env_plots/Salinity_COI_both.png",ggarrange(p3,p4,ncol=2,nrow=2,align="h",common.legend=TRUE,legend="top"),height=8)
```

