---
title: "Combine_plots"
output: html_document
date: "2024-10-08"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r boxplot}

euk <- readRDS("../Plots/Boxplots/18S_rich.rds")
coi <- readRDS("../Plots/Boxplots/COI_MOTU_rich.rds")
pro <- readRDS("../Plots/Boxplots/16S_rich.rds")

ggsave(file="../Plots/Boxplots/All_241008.png",ggarrange(euk,coi,pro,ncol=1,nrow=3,align="h",common.legend=TRUE,legend="top"))
```

```{r nmds}

euk_both <- readRDS("../Plots/NMDS/NMDS_18S_both.rds")
coi_both <- readRDS("../Plots/NMDS/NMDS_COI_both.rds")
pro_both <- readRDS("../Plots/NMDS/NMDS_16S_both.rds")

ggsave(file="../Plots/NMDS/NMDS_both_241008.png",ggarrange(euk_both,coi_both,pro_both,ncol=1,nrow=3,align="h",common.legend=TRUE,legend="top"))
```

```{r hab}

euk_hab_s <-readRDS("../Plots/NMDS/NMDS_18S_hab_sed.rds")
euk_hab_w <-readRDS("../Plots/NMDS/NMDS_18S_hab_wat.rds")
coi_hab_s <- readRDS("../Plots/NMDS/NMDS_70_hab_sed.rds")
coi_hab_w <- readRDS("../Plots/NMDS/NMDS_70_hab_wat.rds")
pro_hab_s <- readRDS("../Plots/NMDS/NMDS_16S_hab_sed.rds")
pro_hab_w <- readRDS("../Plots/NMDS/NMDS_16S_hab_wat.rds")

ggsave(file="../Plots/NMDS/NMDS_all_241008.png",ggarrange(euk_hab_s,euk_hab_w,coi_hab_s,coi_hab_w,pro_hab_s,pro_hab_w,ncol=2,nrow=3,align="h",common.legend=TRUE,legend="top"),
       width = 95,
       height = 150,
       units = "mm",
       dpi = 200)
```


```{r sal}

euk_sal_s <-readRDS("../Plots/NMDS/NMDS_18S_sal_sed.rds")
euk_sal_w <-readRDS("../Plots/NMDS/NMDS_18S_sal_wat.rds")
coi_sal_s <- readRDS("../Plots/NMDS/NMDS_70_sal_sed.rds")
coi_sal_w <- readRDS("../Plots/NMDS/NMDS_70_sal_wat.rds")
pro_sal_s <- readRDS("../Plots/NMDS/NMDS_16S_sal_sed.rds")
pro_sal_w <- readRDS("../Plots/NMDS/NMDS_16S_sal_wat.rds")

ggsave(file="../Plots/NMDS/NMDS_all_sal_241008.png",ggarrange(euk_sal_s,euk_sal_w,coi_sal_s,coi_sal_w,pro_sal_s,pro_sal_w,ncol=2,nrow=3,align="h",common.legend=TRUE,legend="top"),
       width = 95,
       height = 150,
       units = "mm",
       dpi = 200)
```
