---
title: "Env_plots, 18S"
author: "Eva Egelyng Sigsgaard"
date: "2023-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}

library(ggplot2)
library(ggpubr)
library(ggpmisc)
```

```{r get data}

## Get metadata
metadata<-read.table("../Tekstfiler/f_ncbi_metadata_5_01_22.txt", sep="\t", header=T)
#Create extra metadata variables
metadata$sshc<-paste(metadata$substrate_type, metadata$season, metadata$habitat, metadata$cluster, sep="_")
## Get sea distances
areas<-read.table("../Tekstfiler/Mads_metadata_230921_C19.txt", sep="\t", row.names=1, header=T, check.names=FALSE)
## Get salinities
coord<-read.table("../Tekstfiler/merged_metadata_230427.txt", sep="\t", row.names=1, header=T, check.names=FALSE)
```


```{r sed dist}

jaccard<-read.table("../Tekstfiler/Jaccard_18S_sed_all.txt")
metadata$sea_dist<-areas$dist_from_C33.km[match(metadata$cluster,areas$Cluster)]
jaccard$sea_dist<-metadata$sea_dist[match(row.names(jaccard),metadata$sshc)]
jaccard$habitat<-metadata$habitat[match(row.names(jaccard),metadata$sshc)]

p<-ggplot(jaccard, aes(x=sea_dist, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#1B9E77","#E7298A","#A6761D","#666666"),
                     name = "", breaks = sort(unique(metadata$New_Area)),
                     labels = sort(unique(metadata$New_Area)))+
   scale_x_continuous("Distance by sea (km)") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p
```

```{r wat dist}

jaccard_w<-read.table("../Tekstfiler/Jaccard_18S_wat_all.txt")
jaccard_w$sea_dist<-metadata$sea_dist[match(row.names(jaccard_w),metadata$sshc)]
jaccard_w$habitat<-metadata$habitat[match(row.names(jaccard_w),metadata$sshc)]

p2<-ggplot(jaccard_w, aes(x=sea_dist, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#1B9E77","#E7298A","#A6761D","#666666"),
                     name = "", breaks = sort(unique(metadata$New_Area)),
                     labels = sort(unique(metadata$New_Area)))+
   scale_x_continuous("Distance by sea (km)") +
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p2
ggsave(file="../Plots/Env_plots/Sea_dist_18S_both.png",ggarrange(p,p2,ncol=2,nrow=2,align="h",common.legend=TRUE,legend="top"),height=8)
```

```{r salinity sed}

# Add salinity values to dataframe with NMDS scores
metadata$new_name<-paste(metadata$season,metadata$cluster,metadata$habitat,sep="_")
jaccard$new_name<-metadata$new_name[match(row.names(jaccard),metadata$sshc)]
jaccard$salinity<-coord$Salinity[match(jaccard$new_name,row.names(coord))]

p3<-ggplot(jaccard, aes(x=salinity, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#666666","#A6761D","#E7298A","#1B9E77"),
                     name = "", breaks = rev(unique(metadata$New_Area)),
                     labels = rev(unique(metadata$New_Area)))+
   scale_x_continuous("Salinity")+
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p3
```

```{r salinity wat}

jaccard_w$new_name<-metadata$new_name[match(row.names(jaccard_w),metadata$sshc)]
jaccard_w$salinity<-coord$Salinity[match(jaccard_w$new_name,row.names(coord))]

p4<-ggplot(jaccard_w, aes(x=salinity, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#666666","#A6761D","#E7298A","#1B9E77"),
                     name = "", breaks = rev(unique(metadata$New_Area)),
                     labels = rev(unique(metadata$New_Area)))+
   scale_x_continuous("Salinity")+
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p4
ggsave(file="../Plots/Env_plots/Salinity_18S_both.png",ggarrange(p3,p4,ncol=2,nrow=2,align="h",common.legend=TRUE,legend="top"),height=8)
```
```{r org sed}

# Add organic content values to data frame with NMDS scores
jaccard$log_org<-coord$log_Organic_content[match(jaccard$new_name,row.names(coord))]

p3<-ggplot(jaccard, aes(x=log_org, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#666666","#A6761D","#E7298A","#1B9E77"),
                     name = "", breaks = rev(unique(metadata$New_Area)),
                     labels = rev(unique(metadata$New_Area)))+
   scale_x_continuous("log(Organic Content)")+
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p3
```

```{r temp wat}

jaccard_w$temp<-coord$Temperature[match(jaccard_w$new_name,row.names(coord))]

p4<-ggplot(jaccard_w, aes(x=temp, y=NMDS1, shape = habitat, lty=habitat)) +
   geom_point(size=2,aes(color=New_Area))+
   scale_color_manual(values = c("#666666","#A6761D","#E7298A","#1B9E77"),
                     name = "", breaks = rev(unique(metadata$New_Area)),
                     labels = rev(unique(metadata$New_Area)))+
   scale_x_continuous("Temperature")+
   stat_poly_line() +
   stat_poly_eq(label.x=c(0.2,0.2,0.2),label.y=c(1,0.95,0.90))
p4
```
