---
title: "Hap_networks"
author: "Eva Egelyng Sigsgaard"
date: "2023-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE,fig.path = "images/")
```

```{r libraries, message=FALSE}

library("ape")
library("pegas")
library("adegenet")
```

```{r load fasta}

names_sed<-read.table(file="../Tekstfiler/species_sed.tsv", sep="\t")
names_wat<-read.table(file="../Tekstfiler/species_water.tsv", sep="\t")

fasta_sed<-list()

for (i in names_sed$V1){
data<-read.dna(paste("../Tekstfiler/fastafiler/",i,"_sed.fasta",sep=""), format="fasta", as.character = F)
fasta_sed[[i]]<-data
}

fasta_wat<-list()

for (i in names_wat$V1){
data<-read.dna(paste("../Tekstfiler/fastafiler/",i,"_wat.fasta",sep=""), format="fasta", as.character = F)
fasta_wat[[i]]<-data
}
```

```{r align and rename}

sed_ali<-list()

for (i in names(fasta_sed)){
    data<-fasta_sed[[i]]
    dataAli<-clustal(data)
    sed_ali[[i]]<-dataAli
    #checkAlignment(dataAli)
}

saveRDS(sed_ali,"../RDS/sed_ali.rds")

wat_ali<-list()

for (i in names(fasta_wat)){
    data<-fasta_wat[[i]]
    dataAli<-clustal(data)
    wat_ali[[i]]<-dataAli
    #checkAlignment(dataAli)
}

saveRDS(wat_ali,"../RDS/wat_ali.rds")
```

```{r generate networks}

sed_ali<-readRDS("../RDS/sed_ali.rds")
wat_ali<-readRDS("../RDS/wat_ali.rds")

countHap <- function(hap = h, dna = x){
with(
    stack(setNames(attr(hap, "index"), rownames(hap))),
    table(hap = ind, pop = attr(dna, "dimnames")[[1]][values])
    )
}

area_data<-read.table("../Tekstfiler/Mads_metadata.txt", sep="\t", row.names=1, header=T, check.names=FALSE)

n<-length(unique(area_data$Sub_Area))
col.df<-data.frame(area=unique(area_data$Sub_Area),color=brewer.pal(n,"Dark2"))

for (i in names(sed_ali)){
    
    dataAli<-sed_ali[[i]]
    dataHaplo<-haplotype(dataAli)
    dataHaplo<-sort(dataHaplo, what = "labels")
    dataNet<-haploNet(dataHaplo)

    mydata <- as.data.frame(countHap(dataHaplo, dataAli))
    good <- mydata[mydata$Freq == 1,]
    IDs <- strsplit(as.character(good$pop), " ")
    good$IDs <- sapply(IDs, "[[", 2)

    cluster <- strsplit(as.character(good$IDs), "_")
    good$cluster <- sapply(cluster, "[[", 1)

    good$area <- area_data$Sub_Area[match(good$cluster,area_data$Cluster)]
    new.hap <- table(good$hap, good$area)
    colors<-col.df$color[match(colnames(new.hap),col.df$area)]

    png(file=paste("../Plots/Hap_networks/haploNet_",i,"_sed.png",sep=""), width = 600, height = 350, pointsize = 10)
    plot(dataNet, size=attr(dataNet, "freq"), bg=colors,scale.ratio=0.2, pie=new.hap, show.mutation=3)
    legend("bottomright", colnames(new.hap), col=colors, pch=19, ncol=2)
    dev.off()
}

for (i in names(wat_ali)[names(wat_ali)!="Metridia pacifica"]){
    
    dataAli<-wat_ali[[i]]
    dataHaplo<-haplotype(dataAli)
    dataHaplo<-sort(dataHaplo, what = "labels")
    dataNet<-haploNet(dataHaplo)

    mydata <- as.data.frame(countHap(dataHaplo, dataAli))
    good <- mydata[mydata$Freq == 1,]
    IDs <- strsplit(as.character(good$pop), " ")
    good$IDs <- sapply(IDs, "[[", 2)

    cluster <- strsplit(as.character(good$IDs), "_")
    good$cluster <- sapply(cluster, "[[", 1)

    good$area <- area_data$Sub_Area[match(good$cluster,area_data$Cluster)]
    new.hap <- table(good$hap, good$area)
    colors<-col.df$color[match(colnames(new.hap),col.df$area)]

    png(file=paste("../Plots/Hap_networks/haploNet_",i,"_wat.png",sep=""), width = 600, height = 350, pointsize = 10)
    plot(dataNet, size=attr(dataNet, "freq"), bg=colors, scale.ratio=0.2, pie=new.hap, show.mutation=3)
    legend("bottomright", colnames(new.hap), col=colors, pch=19, ncol=2)
    dev.off()
}

# For Metridia pacifica, I used the fast plotting option, as the plot was still not done after several hours

for (i in "Metridia pacifica"){
    
    dataAli<-wat_ali[[i]]
    dataHaplo<-haplotype(dataAli)
    dataHaplo<-sort(dataHaplo, what = "labels")
    dataNet<-haploNet(dataHaplo)

    mydata <- as.data.frame(countHap(dataHaplo, dataAli))
    good <- mydata[mydata$Freq == 1,]
    IDs <- strsplit(as.character(good$pop), " ")
    good$IDs <- sapply(IDs, "[[", 2)

    cluster <- strsplit(as.character(good$IDs), "_")
    good$cluster <- sapply(cluster, "[[", 1)

    good$area <- area_data$Sub_Area[match(good$cluster,area_data$Cluster)]
    new.hap <- table(good$hap, good$area)
    colors<-col.df$color[match(colnames(new.hap),col.df$area)]

    png(file=paste("../Plots/Hap_networks/haploNet_",i,"_wat.png",sep=""), width = 600, height = 350, pointsize = 10)
    plot(dataNet, size=attr(dataNet, "freq"), bg=colors, scale.ratio=0.2, pie=new.hap, show.mutation=3,fast=TRUE)
    legend("bottomright", colnames(new.hap), col=colors, pch=19, ncol=2)
    dev.off()
}

```

```{r PCoA}

#Convert fasta to DNA.bin format
data.bin<-fasta2DNAbin("../Tekstfiler/fastafiler/Bathycoccus prasinos_sed.fasta")

#Compute p-distances
p.dists<-dist.dna(data.bin, model = "raw", variance = FALSE,
         gamma = FALSE, pairwise.deletion = TRUE,
         base.freq = NULL, as.matrix = FALSE)

#Compute PCoA
ord<-pcoa(p.dists, correction="none", rn=NULL)


biplot(ord, Y=NULL, plot.axes = c(1,2), dir.axis1=1,
       dir.axis2=1, rn=NULL, main=NULL, cex=rep(par("cex"), 2))
```

