#interactive map of richness 

#load libraries:
```{r load libraries}

library(crosstalk)
library(leaflet)
library(tidyverse)
library(magrittr)
library(phyloseq)
library(dplyr)
library(leaflet.minicharts)
library(leaflegend)
```

```{r load data}

#Load RDS objects
sed<-readRDS("../RDS/sed_pres_abs.rds")
wat<-readRDS("../RDS/wat_pres_abs.rds")

## Load metatable incl. coordinates, and add column for later use
coord <- read.delim("../Tekstfiler/merged_metadata_230427.txt",row.names=1)
coord$cluster.c<-paste("c",coord$cluster,sep="")

## Load phyloseq object
COSQ_rare2_97 <- readRDS("C:/Users/au620760/OneDrive - Aarhus universitet/COSQ_results_2023/Eva/RDS/COSQ_rare2_correct_pident97.rds")
## Remove cluster 2 (which was only sampled in 1 season)
COSQ_no_c2<-subset_samples(COSQ_rare2_97,!cluster==2)
## Extract metadata and add column with one name for each sample triplicate
meta<-data.frame(sample_data(COSQ_no_c2),check.names=FALSE)
meta$sample<-factor(substr(row.names(meta),
                          1,
                          nchar(row.names(meta))-1))
```

```{r aggregate sed}

# Aggregate samples from the two seasons
sed$cluster<-meta$cluster[match(row.names(sed),meta$sample)]
sed$habitat<-meta$habitat[match(row.names(sed),meta$sample)]
sed_agg<-aggregate(. ~ cluster + habitat, sed, function(x) sum(x))

# Subset into the three habitat types
eel<-sed_agg[sed_agg$habitat=="eelgrass",]
rock<-sed_agg[sed_agg$habitat=="rocks",]
sand<-sed_agg[sed_agg$habitat=="sand",]

## Make new row names specifying cluster
row.names(eel)<-eel$cluster
row.names(rock)<-rock$cluster
row.names(sand)<-sand$cluster

## Remove unnecessary columns
eel<-within(eel,rm(cluster,habitat))
rock<-within(rock,rm(cluster,habitat))
sand<-within(sand,rm(cluster,habitat))

##Convert to presence/absence again (as samples have been aggregated)
eel[eel>0]<-1
rock[rock>0]<-1
sand[sand>0]<-1

# Remove empty colums (species)
eel<-eel[colSums(eel)>0]
rock<-rock[colSums(rock)>0]
sand<-sand[colSums(sand)>0]
```

```{r aggregate wat}

# Aggregate samples from the two seasons
wat$cluster<-meta$cluster[match(row.names(wat),meta$sample)]
wat$habitat<-meta$habitat[match(row.names(wat),meta$sample)]
wat_agg<-aggregate(. ~ cluster + habitat, wat, function(x) sum(x))

# Subset into the three habitat types
eel_w<-wat_agg[wat_agg$habitat=="eelgrass",]
rock_w<-wat_agg[wat_agg$habitat=="rocks",]
sand_w<-wat_agg[wat_agg$habitat=="sand",]

## Make new row names specifying cluster
row.names(eel_w)<-eel_w$cluster
row.names(rock_w)<-rock_w$cluster
row.names(sand_w)<-sand_w$cluster

## Remove unnecessary columns
eel_w<-within(eel_w,rm(cluster,habitat))
rock_w<-within(rock_w,rm(cluster,habitat))
sand_w<-within(sand_w,rm(cluster,habitat))

##Convert to presence/absence again (as samples have been aggregated)
eel_w[eel_w>0]<-1
rock_w[rock_w>0]<-1
sand_w[sand_w>0]<-1

# Remove empty colums (species)
eel_w<-eel_w[colSums(eel_w)>0]
rock_w<-rock_w[colSums(rock_w)>0]
sand_w<-sand_w[colSums(sand_w)>0]
```

```{r sed isr}

hab<-list(eel,rock,sand)
names<-c("eel","rock","sand")

for (i in 1:length(hab)){
  
# Determine occurrence (no. of clusters w. presence) of each species
occ<-hab[[i]] %>%
  colSums(na.rm=TRUE) 

# Transpose site-species matrices
occ_t<-t(hab[[i]])

# Calculation of rarity weights, based on cut-off adapted by Leroy et al. (2012) from Gaston (2003)
rarity.leroy <- rWeights(occ, Qmax = max(occ), Qmin = min(occ),
                         wMethods = "invQ", rCutoff = "Leroy", normalised = T,
                         assemblages = occ_t, extended = F, rounding = 3)

## Rarity cut-off point: 0.2861328 / 4.578125 
## Rarity cut-off point: 0.2283092 / 6.620968 
## Rarity cut-off point: 0.2073361 / 6.427419 

# Calculation of Isr
Isr_leroy<-Isr(occ_t, rarity.leroy, abundance = FALSE, Wmin = min(rarity.leroy), normalise = TRUE)
Isr_leroy<-as.data.frame(Isr_leroy)
Isr_l_sort<-Isr_leroy[order(Isr_leroy$IsrValue,decreasing=TRUE),]
write.table(Isr_l_sort,file=paste("../Tekstfiler/Isr_sed_",names[[i]],".txt",sep=""))
}
```

```{r wat isr}

hab_w<-list(eel_w,rock_w,sand_w)

for (i in 1:length(hab_w)){
  
# Determine occurrence (no. of clusters w. presence) of each species
occ<-hab_w[[i]] %>%
  colSums(na.rm=TRUE) 

# Transpose site-species matrices
occ_t<-t(hab_w[[i]])

# Calculation of rarity weights, based on cut-off adapted by Leroy et al. (2012) from Gaston (2003)
rarity.leroy <- rWeights(occ, Qmax = max(occ), Qmin = min(occ),
                         wMethods = "invQ", rCutoff = "Leroy", normalised = T,
                         assemblages = occ_t, extended = F, rounding = 3)

## Rarity cut-off point: 0.2900391 / 4.640625 
## Rarity cut-off point: 0.2047347 / 6.346774 
## Rarity cut-off point: 0.2122789 / 6.580645 

# Calculation of Isr
Isr_leroy<-Isr(occ_t, rarity.leroy, abundance = FALSE, Wmin = min(rarity.leroy), normalise = TRUE)
Isr_leroy<-as.data.frame(Isr_leroy)
Isr_l_sort<-Isr_leroy[order(Isr_leroy$IsrValue,decreasing=TRUE),]
write.table(Isr_l_sort,file=paste("../Tekstfiler/Isr_wat_",names[[i]],".txt",sep=""))
}
```

```{r prepare metadata}

## Replace habitat names in metadata
meta$habitat<- gsub("EB", "eelgrass", meta$habitat)
meta$habitat<- gsub("EW", "eelgrass", meta$habitat)
meta$habitat<- gsub("RB", "rocks", meta$habitat)
meta$habitat<- gsub("RW", "rocks", meta$habitat)
meta$habitat<- gsub("SB", "sand", meta$habitat)
meta$habitat<- gsub("SW", "sand", meta$habitat)

## Add new sample names used in coord
meta$new_name<-paste(meta$season,"_",meta$cluster,"_",meta$habitat,sep="")
meta<-within(meta,rm("field_replicate","over_median","root"))
meta_d <- meta #in meta_d should contain the columns "cluster", "season", "habitat", "substratetype", "sample", and "new_name"
meta_d<-meta_d %>% distinct() 
row.names(meta_d)<-meta_d$sample
meta_d<-within(meta_d,rm("sample"))

#add coordinates
meta_d$Latitude<-coord$Latitude[match(meta_d$new_name,row.names(coord))] 
meta_d$Longitude<-coord$Longitude[match(meta_d$new_name,row.names(coord))]
```

```{r load isr}

sed_eel<-read.table("../Tekstfiler/Isr_sed_eel.txt")
sed_rock<-read.table("../Tekstfiler/Isr_sed_rock.txt")
sed_sand<-read.table("../Tekstfiler/Isr_sed_sand.txt")

wat_eel<-read.table("../Tekstfiler/Isr_wat_eel.txt")
wat_rock<-read.table("../Tekstfiler/Isr_wat_rock.txt")
wat_sand<-read.table("../Tekstfiler/Isr_wat_sand.txt")
```

```{r prepare maps}

isr_tabs<-list(sed_eel,sed_rock,sed_sand,wat_eel,wat_rock,wat_sand)

for (i in 1:length(isr_tabs)){
  
## Make column to allow matching with metadata
isr_tabs[[i]]$cluster<-coord$cluster[match(row.names(isr_tabs[[i]]),coord$cluster)]
isr_tabs[[i]]$new_name<-paste("spring","_",isr_tabs[[i]]$cluster,"_rocks",sep="")

## Add coordinates from metadata to ASV table
isr_tabs[[i]]$Latitude<-coord$Latitude[match(isr_tabs[[i]]$new_name,row.names(coord))]
isr_tabs[[i]]$Longitude<-coord$Longitude[match(isr_tabs[[i]]$new_name,row.names(coord))]

#round up the Isr values
isr_tabs[[i]]$IsrValue<-round(isr_tabs[[i]]$IsrValue,2)
}
```

```{r sed eel}

isr_sed<-isr_tabs[[1]]

numPal <- colorNumeric("YlOrRd", isr_sed$IsrValue)

map_rar_sed <- leaflet(isr_sed, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_sed$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_sed", height = "100%")

print(map_rar_sed)
```

```{r sed rock}

isr_sed<-isr_tabs[[2]]

numPal <- colorNumeric("YlOrRd", isr_sed$IsrValue)

map_rar_sed <- leaflet(isr_sed, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_sed$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_sed", height = "100%")

print(map_rar_sed)
```

```{r sed sand}

isr_sed<-isr_tabs[[3]]

numPal <- colorNumeric("YlOrRd", isr_sed$IsrValue)

map_rar_sed <- leaflet(isr_sed, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_sed$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_sed", height = "100%")

print(map_rar_sed)
```

```{r wat eel}

isr_wat<-isr_tabs[[4]]

numPal <- colorNumeric("YlOrRd", isr_wat$IsrValue)

map_rar_wat <- leaflet(isr_wat, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_wat$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_wat", height = "100%")

print(map_rar_wat)
```

```{r wat rock}

isr_wat<-isr_tabs[[5]]

numPal <- colorNumeric("YlOrRd", isr_wat$IsrValue)

map_rar_wat <- leaflet(isr_wat, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_wat$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_wat", height = "100%")

print(map_rar_wat)
```

```{r wat sand}

isr_wat<-isr_tabs[[6]]

numPal <- colorNumeric("YlOrRd", isr_wat$IsrValue)

map_rar_wat <- leaflet(isr_wat, width = "100%", height = 300) %>%
  addTiles() %>%
  addSymbolsSize(values = ~8000,
                 lat = ~Latitude, 
                 lng = ~Longitude,
                 shape = 'circle',
                 color = 'black',
                 fillColor = ~numPal(IsrValue),
                 opacity = .8,
                 baseSize = 10) %>%
  addLegendNumeric(
    pal = numPal, 
    title = "Rarity index",
    shape = 'stadium',
    values = isr_wat$IsrValue, 
    fillOpacity = .5,
    decreasing = TRUE,
    position = 'topright') %>%
  setView(11.688598945812004, 56.00717750251805, zoom = 6)

# render the map using leafletOutput
leafletOutput("map_rar_wat", height = "100%")

print(map_rar_wat)
```