---
title: "Rich_depth"
author: "Eva Sigsgaard"
date: "2025-01-27"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries}
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggpubr)
library(ggpmisc)
library("gridExtra")
library(RColorBrewer)
library(hrbrthemes)
library(viridis)
library(cowplot)
library(readxl)
library(e1071)
library(vegan)
library(phyloseq)
```

```{r load datasets}

## Import rarefied 18S dataset
rare_18S <- readRDS("../../RDS/18S_no_c2_3reps.rds")

## Import taxonomy table from before rarefying
tax <- read.delim("../../Tekstfiler/18S/18S_classified_all.tsv", sep="\t", row.names=NULL,check.names=FALSE)
# Load table with corrected phylum names and marine/non-marine
tax_cur<-read.table("../../Tekstfiler/18S/18S_classified_phy_class_curated.tsv",sep="\t",header=T)
# Remove non-marine classes from taxonomy table
tax_mar <- tax[!tax$class %in% tax_cur$class[tax_cur$marine=="no"],]
# Extract OTU counts
#View(tax_mar)
raw_18S <- tax_mar[,27:3785]

## Get rarefied COI dataset
rare_COI <- readRDS("../../RDS/COI_no_c2_3reps.rds")

## Import raw COI table incl. taxonomy
pident70<-read.table("../../Tekstfiler/COI/COI_70/COSQ_final_dataset_cleaned_pident_70.tsv",sep="\t", header=T, check.names=F)
# Removing taxa that contain NA in both phylum and class
tax_phy_class<-subset(pident70, !(is.na(pident70$phylum)&is.na(pident70$class)))
## Import manually curated table
tax_env<-read.table("../../Tekstfiler/COI/COI_70/COSQ_pident70_phy_class_curated.tsv",sep="\t", header=T)
## Remove non-marine classes
COI_mar <- pident70[!pident70$class %in% tax_env$class[tax_env$marine=="no"],]
# Extract OTU counts
#View(COI_mar)
raw_COI <- COI_mar[,29:3709]

## Import rarefied 16S dataset
rare_16S <- readRDS("../../RDS/16S_no_c2_3reps.rds")

## Load raw 16S table
raw_16S <- read.table("../../Tekstfiler/16S/cleaned_otu_silva_EES3.txt", sep="\t", header=T, row.names=1,check.names=F)

## Get metadata. Using the metadata file for 16S across barcodes, as this one has a column with the same names used in the raw (unrarefied) tables
sam <-read.table("../../Tekstfiler/16S/metadata_rarefy_dada2.txt", sep="\t", header=T, row.names=1,check.names=F)
sam$new_name <- paste(sam$substrate_type,sam$season,sam$habitat,sam$cluster,sep="_")
```

```{r rarecurves 18S}

raw_18S_t <- as.data.frame(t(raw_18S))

##Add sample name (root name) and use it to add metadata
raw_18S_t$sample<- sapply(strsplit(as.character(rownames(raw_18S_t)), "_"), head, 1)
raw_18S_t$season <- sam$season[match(raw_18S_t$sample,row.names(sam))]
raw_18S_t$habitat <- sam$habitat[match(raw_18S_t$sample,row.names(sam))]
raw_18S_t$substrate <- sam$substrate_type[match(raw_18S_t$sample,row.names(sam))]

# Extract count matrix
counts <- raw_18S_t %>% select(where(is.numeric))

# Metadata
meta <- raw_18S_t %>% select(sample, season, habitat, substrate)

# Calculate sequencing depths per replicate
sample_sums <- rowSums(counts)

# Define common rarefaction depths
depths <- seq(1, 5000, by = 250)

# Vectorized rarefaction (fast!)
rare_mat <- sapply(depths, function(d) rarefy(counts, sample = d))
rare_mat <- t(rare_mat)
rownames(rare_mat) <- depths
colnames(rare_mat) <- raw_18S_t$sample

# Convert to tidy long format
rare_df <- as.data.frame(rare_mat)
rare_df$depth <- depths

rare_long_18S <- rare_df %>%
  pivot_longer(-depth, names_to = "sample", values_to = "richness") %>%
  left_join(meta, by = "sample")

# Plot rarefaction curves
rarecurve_18S <- ggplot(rare_long_18S, aes(depth, richness, group = sample)) +
  geom_line(alpha = 0, color = "lightblue") +
  geom_smooth(se = FALSE, method = "loess", span = 0.3, color = "black") +
  facet_grid(substrate + season ~ habitat) +
  theme_bw()

rarecurve_18S
```

```{r rarecurves COI}

raw_COI_t <- as.data.frame(t(raw_COI))

##Add sample name (root name) and use it to add metadata
raw_COI_t$sample<- sapply(strsplit(as.character(rownames(raw_COI_t)), "_"), head, 1)
raw_COI_t$season <- sam$season[match(raw_COI_t$sample,row.names(sam))]
raw_COI_t$habitat <- sam$habitat[match(raw_COI_t$sample,row.names(sam))]
raw_COI_t$substrate <- sam$substrate_type[match(raw_COI_t$sample,row.names(sam))]

# Extract count matrix
counts <- raw_COI_t %>% select(where(is.numeric))

# Metadata
meta <- raw_COI_t %>% select(sample, season, habitat, substrate)

# Calculate sequencing depths per replicate
sample_sums <- rowSums(counts)

# Define common rarefaction depths
depths <- seq(1, 5000, by = 250)

# Vectorized rarefaction (fast!)
rare_mat <- sapply(depths, function(d) rarefy(counts, sample = d))
rare_mat <- t(rare_mat)
rownames(rare_mat) <- depths
colnames(rare_mat) <- raw_COI_t$sample

# Convert to tidy long format
rare_df <- as.data.frame(rare_mat)
rare_df$depth <- depths

rare_long_COI <- rare_df %>%
  pivot_longer(-depth, names_to = "sample", values_to = "richness") %>%
  left_join(meta, by = "sample")

# Plot rarefaction curves
rarecurve_COI <- ggplot(rare_long_COI, aes(depth, richness, group = sample)) +
  geom_line(alpha = 0, color = "lightblue") +
  geom_smooth(se = FALSE, method = "loess", span = 0.3, color = "black") +
  facet_grid(substrate + season ~ habitat) +
  theme_bw()

rarecurve_COI
```
```{r rarecurves 16S}

raw_16S_t <- as.data.frame(t(raw_16S))

##Add sample name (root name) and use it to add metadata
raw_16S_t$sample<- sapply(strsplit(as.character(rownames(raw_16S_t)), "_"), head, 1)
raw_16S_t$season <- sam$season[match(raw_16S_t$sample,row.names(sam))]
raw_16S_t$habitat <- sam$habitat[match(raw_16S_t$sample,row.names(sam))]
raw_16S_t$substrate <- sam$substrate_type[match(raw_16S_t$sample,row.names(sam))]

# Extract count matrix
counts <- raw_16S_t %>% select(where(is.numeric))

# Metadata
meta <- raw_16S_t %>% select(sample, season, habitat, substrate)

# Calculate sequencing depths per replicate
sample_sums <- rowSums(counts)

# Define common rarefaction depths
depths <- seq(1, 5000, by = 250)

# Vectorized rarefaction (fast!)
rare_mat <- sapply(depths, function(d) rarefy(counts, sample = d))
rare_mat <- t(rare_mat)
rownames(rare_mat) <- depths
colnames(rare_mat) <- raw_16S_t$sample

# Convert to tidy long format
rare_df <- as.data.frame(rare_mat)
rare_df$depth <- depths

rare_long_16S <- rare_df %>%
  pivot_longer(-depth, names_to = "sample", values_to = "richness") %>%
  left_join(meta, by = "sample")

# Plot rarefaction curves
rarecurve_16S <- ggplot(rare_long_16S, aes(depth, richness, group = sample)) +
  geom_line(alpha = 0, color = "lightblue") +
  geom_smooth(se = FALSE, method = "loess", span = 0.3, color = "black") +
  facet_grid(substrate + season ~ habitat) +
  theme_bw()

rarecurve_16S
```

```{r prepare 18S}

## Get OTU table
otu_18S<-data.frame(otu_table(rare_18S),check.names=F)

##Convert to presence/absence
otu_18S[otu_18S>0]<-1

## Get MOTU richness
rich_18S <- as.data.frame(otu_18S %>% rowSums())
names(rich_18S)[1]<-"richness"

## Calculate read depths
depth_18S<-as.data.frame(colSums(raw_18S))
names(depth_18S)[1]<-"depth"

## Add new sample names to depth table
depth_18S$root <- sapply(strsplit(as.character(row.names(depth_18S)), "_"), head, 1)
depth_18S$new_name <- sam$new_name[match(depth_18S$root,row.names(sam))]

## Sum read depths of PCR replicates and filter replicates
depth_18S <- within(depth_18S,rm("root"))
depth_18S_agg <- aggregate(depth ~ new_name, data=depth_18S, FUN = sum)

hist(depth_18S_agg$depth)
hist(log(depth_18S_agg$depth))

## Export depths for use in modeling
write.table(depth_18S_agg,"../../Tekstfiler/18S/18S_seqdepths.txt",sep="\t")

## Add depth to richness table
rich_18S$depth <- depth_18S_agg$depth[match(row.names(rich_18S),depth_18S_agg$new_name)]
```

```{r 18S scatter depth richness}

## Add habitat to depth table
rich_18S$habitat <- sam$habitat[match(row.names(rich_18S),sam$new_name)]

## Add substrate to depth table
rich_18S$substrate <- sam$substrate_type[match(row.names(rich_18S),sam$new_name)]

cols <- c("sediment"='#d8b365',"water"='#5ab4ac')

p<-ggplot(rich_18S, aes(x = depth, y = richness, colour = substrate)) +
  geom_point(size=2,aes(color=substrate)) +
  scale_color_manual(values = cols,
                     name = "", breaks = c("sediment","water"),
                     labels = c("sediment","water"))+
  geom_smooth(method = "lm", se = FALSE, linewidth = .5) + #> `geom_smooth()` using formula 'y ~ x'
   stat_poly_line() +
stat_poly_eq(use_label(c("n","R2", "P"), sep = "*\"; \"*"),small.p = getOption("ggpmisc.small.p", default = TRUE),p.digits=4,label.x=c(0.05,0.05,0.05),label.y=c(1,0.95,0.90))+
  labs(x="Read depth", y="MOTU Richness")+
  theme_classic()+
  theme(legend.position = "NA")
p
```

```{r prepare COI}

## Get OTU table
otu_COI<-data.frame(otu_table(rare_COI),check.names=F)

##Convert to presence/absence
otu_COI[otu_COI>0]<-1

## Get MOTU richness
rich_COI <- as.data.frame(otu_COI %>% rowSums())
names(rich_COI)[1]<-"richness"

## Calculate read depths
depth_COI<-as.data.frame(colSums(raw_COI))
names(depth_COI)[1]<-"depth"

## Add new sample names to depth table
depth_COI$root <- sapply(strsplit(as.character(row.names(depth_COI)), "_"), head, 1)
depth_COI$new_name <- sam$new_name[match(depth_COI$root,row.names(sam))]

## Sum read depths of PCR replicates and filter replicates
depth_COI <- within(depth_COI,rm("root"))
depth_COI_agg <- aggregate(depth ~ new_name, data=depth_COI, FUN = sum)

## Export depths for use in modeling
write.table(depth_COI_agg,"../../Tekstfiler/COI/COI_seqdepths.txt",sep="\t")

## Add depth to richness table
rich_COI$depth <- depth_COI_agg$depth[match(row.names(rich_COI),depth_COI_agg$new_name)]
```

```{r COI scatter depth richness}

## Add habitat to depth table
rich_COI$habitat <- sam$habitat[match(row.names(rich_COI),sam$new_name)]

## Add substrate to depth table
rich_COI$substrate <- sam$substrate_type[match(row.names(rich_COI),sam$new_name)]

q<-ggplot(rich_COI, aes(x = depth, y = richness, color=substrate)) +
  geom_point(size=2,aes(color=substrate)) +
   scale_color_manual(values = cols,
                     name = "", breaks = c("sediment","water"),
                     labels = c("sediment","water"))+
  geom_smooth(method = "lm", se = FALSE, linewidth = .5) + #> `geom_smooth()` using formula 'y ~ x'
   stat_poly_line() +
stat_poly_eq(use_label(c("n","R2", "P"), sep = "*\"; \"*"),small.p = getOption("ggpmisc.small.p", default = TRUE),p.digits=4,label.x=c(0.05,0.05,0.05),label.y=c(1,0.95,0.90))+
  labs(x="Read depth", y="MOTU Richness")+
  theme_classic()+
  theme(legend.position = "NA")
q
```

```{r prepare 16S}

## Get OTU table
otu_16S<-data.frame(otu_table(rare_16S),check.names=F)

##Convert to presence/absence
otu_16S[otu_16S>0]<-1

## Get MOTU richness
rich_16S <- as.data.frame(otu_16S %>% rowSums())
names(rich_16S)[1]<-"richness"

## Calculate read depths
depth_16S<-as.data.frame(colSums(raw_16S))
names(depth_16S)[1]<-"depth"

## Add new sample names to depth table
depth_16S$root <- sapply(strsplit(as.character(row.names(depth_16S)), "_"), head, 1)
depth_16S$new_name <- sam$new_name[match(depth_16S$root,row.names(sam))]

## Sum read depths of PCR replicates and filter replicates
depth_16S <- within(depth_16S,rm("root"))
depth_16S_agg <- aggregate(depth ~ new_name, data=depth_16S, FUN = sum)

## Export depths for use in modeling
write.table(depth_16S_agg,"../../Tekstfiler/16S/16S_seqdepths.txt",sep="\t")

## Add depth to richness table
rich_16S$depth <- depth_16S_agg$depth[match(row.names(rich_16S),depth_16S_agg$new_name)]
```

```{r 16S scatter depth richness}

## Add habitat to depth table
rich_16S$habitat <- sam$habitat[match(row.names(rich_16S),sam$new_name)]

## Add substrate to depth table
rich_16S$substrate <- sam$substrate_type[match(row.names(rich_16S),sam$new_name)]

r<-ggplot(rich_16S, aes(x = depth, y = richness, color=substrate)) +
  geom_point(size=2,aes(color=substrate)) +
    scale_color_manual(values = cols,
                     name = "", breaks = c("sediment","water"),
                     labels = c("sediment","water"))+
  geom_smooth(method = "lm", se = FALSE, linewidth = .5) + #> `geom_smooth()` using formula 'y ~ x'
   stat_poly_line() +
stat_poly_eq(use_label(c("n","R2", "P"), sep = "*\"; \"*"),small.p = getOption("ggpmisc.small.p", default = TRUE),p.digits=4,label.x=c(0.05,0.05,0.05),label.y=c(1,0.95,0.90))+
  labs(x="Read depth", y="MOTU Richness")+
  theme_classic()+
  theme(legend.position = "top")

r
```

```{r combine plots}

# Rarefaction plots
p1 <- ggdraw() + draw_label("18S", angle = 90, x = 0.02, y = 0.5, fontface = "bold") +
      draw_plot(rarecurve_18S, x = 0.05, width = 0.95)

p2 <- ggdraw() + draw_label("COI", angle = 90, x = 0.02, y = 0.5, fontface = "bold") +
      draw_plot(rarecurve_COI, x = 0.05, width = 0.95)

p3 <- ggdraw() + draw_label("16S", angle = 90, x = 0.02, y = 0.5, fontface = "bold") +
      draw_plot(rarecurve_16S, x = 0.05, width = 0.95)

final <- plot_grid(p1, p2, p3, ncol = 1, align = "v")

ggsave("../../Plots/Rarefaction.png", final, width = 30, height = 40, units = "cm")

# Scatter plots of depth vs. richness
ggsave(file="../../Plots/Scatter_rich/Depth_rich.png",ggarrange(p,q,r,nrow=1,ncol=3,align="h",common.legend=TRUE,legend="top"),width=30,height=15,units="cm")

```